import JSZip from 'jszip';
import type { BrandKit } from './types';

export async function downloadBrandKitAsZip(brandKit: BrandKit, generatedImages: string[] = []) {
    const zip = new JSZip();

    // Create brand info JSON
    const brandInfo = {
        brandName: brandKit.brandName,
        tagline: brandKit.tagline,
        mission: brandKit.mission,
        personality: brandKit.personality,
        colorPalette: brandKit.colorPalette,
        logoPrompt: brandKit.logoPrompt,
        createdAt: brandKit.createdAt || new Date().toISOString(),
    };

    zip.file('brand-info.json', JSON.stringify(brandInfo, null, 2));

    // Create README
    const readme = `# ${brandKit.brandName}

${brandKit.tagline}

## Mission
${brandKit.mission}

## Brand Personality
${brandKit.personality.join(', ')}

## Color Palette
- Primary: ${brandKit.colorPalette.primary}
- Secondary: ${brandKit.colorPalette.secondary}
- Accent: ${brandKit.colorPalette.accent}

## Logo Prompt
${brandKit.logoPrompt}

---
Generated by Brandix.ai
`;

    zip.file('README.md', readme);

    // Download logo if available
    if (brandKit.logoUrl) {
        try {
            const logoResponse = await fetch(brandKit.logoUrl);
            const logoBlob = await logoResponse.blob();
            zip.file('logo.png', logoBlob);
        } catch (error) {
            console.error('Failed to download logo:', error);
        }
    }

    // Download generated images if available
    if (generatedImages.length > 0) {
        const imagesFolder = zip.folder('images');
        if (imagesFolder) {
            for (let i = 0; i < generatedImages.length; i++) {
                try {
                    const imageResponse = await fetch(generatedImages[i]);
                    const imageBlob = await imageResponse.blob();
                    imagesFolder.file(`image-${i + 1}.png`, imageBlob);
                } catch (error) {
                    console.error(`Failed to download image ${i + 1}:`, error);
                }
            }
        }
    }

    // Generate and download the zip file
    const zipBlob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(zipBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${brandKit.brandName.replace(/\s+/g, '-').toLowerCase()}-brand-kit.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
